[package]
name = "jqoiview"
description = "A simple QOI image format viewer"
repository = "https://github.com/Jasper-Ty/jqoiview/"
keywords = ["qoi", "image"]
license = "MIT"
version = "0.5.0"
edition = "2021"

[dependencies]
sdl2 = "0.35"
